### ISSUE TITLE
Is Vue the "gateway drug" to Angular?

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e28-fall19#105]
I was struck, watching the Week 09 lectures, just how similar vue-router is to Angular's routing system:

[https://angular.io/guide/router](https://angular.io/guide/router)

Granted, Vue offers a lot of flexibility regarding official or third-party modules to use or not use in a project, whereas Angular forces a monolithic framework down the developer's throat, but if we were to build an application from the ground up, using the comprehensive approach, and using official tools like vue-router and vuex, it seems like we arrive at something pretty similar to "Diet Angular" as I'll call it.

I'm not saying that's a bad thing--in fact, it seems like a lot of what we're doing with Vue translates pretty easily over to Angular, which is probably a good thing! Still, it struck me how similar the two frameworks are, right down to solutions for virtual routing in SPAs.

**Comment by rokmesojedec** [comment]
Evan You, Vue's creator said in an [interview](https://web.archive.org/web/20170603052649/https://betweenthewires.org/2016/11/03/evan-you/): 
>"I figured, what if I could just extract the part that I really liked about Angular and build something really lightweight without all the extra concepts involved? "

He designed Vue by using Angular as a point of reference. That's why there's many similarities between the two.

Personally, I seem to prefer Vue to Angular as I seem to be able to implement things faster with it. 

However, I would like to add that personal preference should not be the main driver behind choosing your framework (or lack of it). At the end these are all tools at our disposal and we should use the right tool for the task at hand.

**Comment by susanBuck** [comment]
Tagging post #87 on this, as anyone reading this thread will also find that discussion interesting.
