### ISSUE TITLE
zipfoods img binding issue with product images

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e28-fall19#107]
I followed all of the instructions in the [Week 09 notes](https://hesweb.dev/e28/notes#/vue/zipfoods-start) as well as the videos, but no matter what I tried, I could not get WebPack to compile my application so that my product images would be visible so long as they resided within /src/assets/images/products/. However, moving them to /public/products/ solved the problem and allowed product image loading without a hitch.

I wonder if this is related to [Issue # 106](https://github.com/susanBuck/e28-fall19/issues/106) and single quotes being automatically converted into double quotes within VS Code? I too am suffering from that annoyance. Still, I would think that by using outer double quotes and inner single quotes, the interpolation and string concatenation should work properly?

**Comment by gaderrick** [comment]
I think it is... I've spent two hours trying to debug the single quote issue to no avail. I did manage to get the images to work in the /images/products/ folder doing this:

```html
<img
            v-bind:alt="'Product image of '+ product.name"
            :src="require('../assets/images/products/' + product.id + '.jpg')"
/>
```

I'm going to run back through all the VSCode configs to see if I missed something Susan did, but for the time being the work around works.

**Comment by kreinholz** [comment]
`require!` I do believe you've found a viable solution! I too spent over 2 hours troubleshooting image loading, and ultimately resorted to moving the product images to /public in order to avoid WebPack compilation making my images disappear. It is a frustrating issue to say the least.

Thanks for the tip! I don't think you're missing anything...but I'd like to fix my VS Code configuration as I'm used to using single quotes and have had to adapt to double quotes...until the image loading issue, it was never an issue, merely an annoyance, but I would like to get VS Code configured the way _I_ want it to believe. Aside from this one hiccup, it's a great editor and I'm loving it!

**Comment by kreinholz** [comment]
That did the trick, @gaderrick! Thanks again!

**Comment by pingji00** [comment]
`require` helps me! Thank you! @gaderrick

**Comment by apatruno618** [comment]
`require` helped me too. Thank you @gaderrick

**Comment by susanBuck** [comment]
Just posted some of this on #106 but wanted to echo it here since it's related...

Below are the VSCode settings I have related to vetur/single-quotes, which makes it favor **single-quotes** as the "primary quote":

```json
"vetur.format.defaultFormatterOptions": {
        "prettier": {
            "singleQuote": true
        },
        "prettyhtml": {
            "singleQuote": true
        }
    },
```


And here is how I set the image src:
```html
<img
            class='product-thumb'
            :alt='"Product image of  " + product.name'
            :src='"./../assets/images/products/" + product.id + ".jpg"'
        />

```

So the v-bind `src` value is surrounded in **single quotes, that encapsulates the entire expression.**
The expression then is made up of a string + variable + string, where each string is surrounded by double quotes.

It would follow the same pattern if I was using **require**:
```html
 <img
            class="product-thumb"
            :alt="'Product image of ' + product.name"
            :src="require('./../assets/images/products/' + product.id + '.jpg')"
        />
```


## Double quotes approach
If I didn't have VSCode/vetur configured to use single quotes, here's how I would write it without require:

```html
<img
            class="product-thumb"
            :alt="'Product image of ' + product.name"
            :src="'./../assets/images/products/' + product.id + '.jpg'"
        />
```

And here's how I would write it with require:
```html
<img
            class="product-thumb"
            :alt="'Product image of ' + product.name"
            :src="require('./../assets/images/products/' + product.id + '.jpg')"
        />
```

## Notes
+ Use your "primary" quote to surround the expression/value.
+ Use your "secondary" quote to surround strings within the expression value.
+ Vetur and its linters uses double quotes as the "primary" quote by default.
    + To overwrite this and use single quotes, edit your settings (see my example settings above)
    + Refer to my [VSCode notes](https://hesweb.dev/e28/notes#/misc/vscode?jump=settings) for the specific location of where VSCode's settings file is located.
+ No wrong or right regarding double vs. single quotes; matter of personal/team preference.
+ The `require` method is a method used in SFCs and processed by `vue-loader` (the loader Vue CLI's webpack config uses to compile SFCs). You can learn more about this method here: https://vue-loader.vuejs.org/guide/asset-url.html#asset-url-handling.

**Comment by extra808** [comment]
I [commented on a closed issue](/susanBuck/e28-fall19/issues/95#issuecomment-550146484) that Webpack (I'm assuming) wasn't handling the product image assets unless I used require().

**Comment by susanBuck** [comment]
@extra808 FYI Just replied and re-opened the other thread you referenced.

**Comment by kreinholz** [comment]
I can confirm that making these changes to my VS Code settings on Windows 10, single quotes are now the default for external quotes, and are no longer converted to double-quotes. Woo hoo! 🙌

It is also no longer necessary to wrap the img :src binding within 'require()'.

**Comment by susanBuck** [comment]
Correction to my above post - the **double quotes approach** I showed will build w/o error, however, the images will be broken in the browser because the path will incorrectly be attempting to pull the images from the assets folder:

```html
<img data-v-1acef832="" src="./../assets/images/products/1.jpg" class="product-thumb">
```

So if you want to use double quotes, you do in fact have to use the `require` method.

```php
<img
                class="product-thumb"
                :src="require('./../assets/images/products/' + product.id + '.jpg')"
            />
```

If you switch Vetur to prefer single quotes, you can but do not have to use the `require` method.

Hat tip to @extra808 for bringing this up again in thread #95.
