### ISSUE TITLE
My-JSON-server images

### ISSUE THREAD

**Issue by ihimawan** [susanBuck/e28-fall19#118]
I was wondering if any of you know a way to use https://my-json-server.typicode.com/ with images? I couldn't find it anywhere for `my-json-server` at least.

I was able to find something of use in https://github.com/typicode/json-server though. It seems a lot more flexible but that means I'm going to have to deploy it to a server, which I don't mind to do but I was trying to see if there's any easier solution.

Let me know if you guys have any better solution that I'm not seeing?

Thanks.

**Comment by susanBuck** [comment]
I don't think it's necessary for the server API to include the images themselves. 

I'd have the API deliver the image names, and then load those images from your server or - in the real world - you'd probably load them from a CDN.

Let me know if there's some particular reason you were thinking the images should come from the API, or if the above suggestions fits your needs.

**Comment by kreinholz** [comment]
@ihimawan, I agree with our professor on this one. "Mocking" the server REST API data, I assume you would have to serve the images locally from your Vue development server (or your Apache server when deployed to production).

I did some work with REST APIs and server + client interaction in [CSCI E-31](https://www.extension.harvard.edu/course-catalog/courses/crn/25038), a fantastic class on the MEAN stack (Node.js/Express server, MongoDB--a NoSQL database, and Angular toward the end of the course as a front-end framework), and I recall images being a bit of a pain to work with. Even working with a real server and interacting with it via a REST API, there's some extra stuff you have to do on the server-side to deal with images (especially Create operations) that make them more difficult than e.g. _text_. Because all the text, we could push from the Angular front-end to the MongoDB server via the REST API. But with images, you have to store the images locally on your server's filesystem. If you can't handle images with a *real* server, I highly doubt you can do it with a mock one.

Incidentally, I believe [CSCI E-15](https://hesweb.dev/e15) would be a wonderful companion to this, our current class, since we're already using an Apache server, and that class will allow us to dive into the workings of that server, and develop the other side of the server-client coin to build fully RESTful apps with a Vue.js front-end and PHP back-end. I'd also highly, highly recommend **CSCI E-31** as noted above, especially if you're enjoying working with JavaScript and want to learn server-side JavaScript (and can put up with a few weeks of Angular and TypeScript near the end of the course--honestly after this class, I think it'll come pretty easy given the similarities between Vue.js and Angular).

**Comment by ihimawan** [comment]
@susanBuck @kreinholz thanks for the feedback you guys!
