### ISSUE TITLE
Is it fine if i use a JSON, instead of fake API?

### ISSUE THREAD

**Issue by coinshot** [susanBuck/e28-fall19#124]
Through the Vue Router, I am passing a "**slug**" instead of an "**id**", to load up the individual pages (for readability purpose). The "**my-json-server.com**" apparently allows making filtered requests only by "**id**". I could make a quick Express app but it's a bit overkill so I am getting all the data when the app loads up and I do the filtering later through action in some Vuex module. 

I can still use "**my-json-server.com**" but, _in my case_, their limited filtering feature to make API calls do not serve any purpose (not on my project) compare to having a local JSON.

So wrt the project 3 guidelines, would it be fine if I just place my JSON file in the public folder and use its relative path as URL for the AJAX call? I am still using AXIOS and everything resembles the way we call a real API.

**Comment by susanBuck** [comment]
Yup, that's fine!

**Comment by kreinholz** [comment]
Yes, commenting on a closed post, but this is a lifesaver! Another limitation with my-json-server.com that I've come across is a maxContentLength size limitation...very annoying, and had me pondering whether to whip up a quick Node.js/Express server in order to get around it! Knowing we can "mock" our server API another way is a big relief!
