### ISSUE TITLE
CSS opacity renders correctly locally, but not on my DigitalOcean server

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#144]
Hi guys,

Really hoping someone can help me solve this mystery.  I tried to get fancy with opacity in CSS on  Project 3. It looked totally fine on my local server, but once I pushed to production on DigitalOcean, the opacity no longer worked. Instead of going partially transparent, it's 100% transparent. 

I'm using the same Chrome browser for both my local server and production server. I thought CSS rendering would all be based on the client-side settings, so I'm confused on what's going on.

Any ideas?

Best,
Carly

**Comment by extra808** [comment]
Very odd, are you sure the property is being applied in production? What do you see when you inspect the element? Perhaps Webpack's compilation of the CSS is resulting in a source order where the selector with the property and value you expect comes before a different selector.

**Comment by ihimawan** [comment]
.. and have you tried clearing the cache?

**Comment by cgloge** [comment]
Thanks for the help guys!

I did clear the cache and when I inspect the element, the CSS does look correct.

Will keep digging and will report back if I figured it out!

**Comment by extra808** [comment]
Firefox 70's inspector can help. Unused properties are greyed out, properties overridden by other declarations are crossed out (I think vendor-prefixed properties not supported by the browser are also crossed out), invalid properties/values are marked but since it works when served locally, that won't be a problem for you. You can filter by property name to more easily see them all together.

I'm sure other inspectors have their own helpful features, I'm just more familiar with Firefox's.

**Comment by susanBuck** [comment]
Hi @cgloge - Still debugging this? If so, share your URL with us and tell us the specific selector/element is that you're fighting with.

**Comment by cgloge** [comment]
I ended up removing the transparency on hover. Ultimately, I realized that
complex hover states are a thing of the past anyway since they aren't
mobile friendly.

I'm going to try to get to the root of the issue while working on Project 4
so I'll report back if I figure it out.

Thanks so much for your help everyone!
