### ISSUE TITLE
Vuex - persisting data on refresh?

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#154]
I have the Vuex functionality wired up and I'm able to add/remove items from the state variable (an array of items), but when I force a page reload/refresh, the array in my store "disappears." This appears to be a known issue. I found the following article that suggests a solution/workaround:

https://stackoverflow.com/questions/43027499/vuex-state-on-page-refresh

@susanBuck - do we need to incorporate this type of functionality into our P4? Has anyone else noticed the same behavior and/or have a solution?

**Comment by gaderrick** [comment]
I also came across this functionality, but it is kind of annoying:
```javascript
window.onbeforeunload = function() {
  return 'Choices have consequences';
};
```

**Comment by kreinholz** [comment]
@gaderrick, does localStorage not get the job done (i.e. do you experience this issue with the most current zipfoods commits made by @susanBuck), or are you still experiencing this issue? I would think that checking localStorage at page load and updating the state accordingly would solve the problem?

Ironically, reading your StackOverflow link, I was contemplating integrating a Firebase login to my app, so your post couldn't be more timely!

**Comment by gaderrick** [comment]
Localstorage works great, but the Vuex "store" doesn't persist through a refresh. I thought the intent was to get away from the localstorage route, but I may have missed something. Glad the link helped though. :)

**Comment by kreinholz** [comment]
I think, because of the nature of client-side application programming, your only options to persist data in the Vuex "store" to survive a hard refresh/page reload (or closing of the browser and revisiting of the site) is either via localStorage, cookies, or server/database integration.

The Vuex store isn't a database, so the state information in it is only designed to last during a user's current session. I don't think this is a flaw with Vuex so much as it is a limitation of client-side application programming. If you want to persist data, you either need a server/database, or to get creative with something like localStorage.

<https://stackoverflow.com/questions/43047219/vuex-store-empty-if-i-refresh-my-webpage/43048031>

I think for our purposes, having your app retrieve data from localStorage and commit this to your Vuex store when it makes sense to do so (whether in App.vue or elsewhere) is the easiest way to have the store behave as though data is being persisted to it.

**Comment by susanBuck** [comment]
@kreinholz hit the nail on the head with his explanation in the above post.

For a metaphor - think about computers - there's permanent storage to the hard drive, and there's short-term storage in RAM. 

Vuex is like the RAM of your SPA, and refreshing the page is the equivalent of restarting your computer. 

If you want data to persist after a page refresh, it must be retrieved from a "hard drive" - whether that be cookies, local storage, or a request to the server.

I've made a note to expound on this with an example in this week's lecture. : )

**Comment by cgloge** [comment]
This is super helpful!

In the case of a recipe site, I think it's ideal to have state persist for the favorite recipes, shopping list, etc for the user. 

Rather than manually committing localStorage data to VueX store, would it make sense to use the [vuex-persist library](https://flaviocopes.com/vuex-persist-localstorage/)? 

Thanks,
Carly

**Comment by susanBuck** [comment]
@cgloge - Yup, `vuex-persist` is a good solution to combine the powers of Vuex + local storage!
