### ISSUE TITLE
Assignment clarification - Week 2, Question 9

### ISSUE THREAD

**Issue by apatruno618** [susanBuck/e28-fall19#16]
Hi @susanBuck , does Question 9 refer to internal or external Javascript? Or should we not worry about that distinction?

**Comment by susanBuck** [comment]
Hi @apatruno618 - It can apply to internal or external.

PS - If you have questions about the "Content check" portion of the assignment, please email them to me directly, per this note you'll see in the assignment each week:

![image](https://user-images.githubusercontent.com/237711/64973698-7a89bb80-d879-11e9-9f0f-9bc5c4d23f30.png)

The only reason I make this request is because students sometimes unknowingly provide hints to questions. The question you've asked here is harmless, but it's better to be safe than sorry. : )
