### ISSUE TITLE
Finally block being weird: running AFTER test assertions

### ISSUE THREAD

**Issue by ihimawan** [susanBuck/e28-fall19#165]
I have code that runs at `beforeMount` like so:

```javascript
this.$store.dispatch('setProfileCollections').then(() => {
  ...
}).catch(() => {
  this.error = true;
})
.finally(() => {
  this.loading = false;
  console.log('[fx]' + this.loading)
})
console.log('[CoreGame]' + this.loading)
```

The test that I have is as follows:
```javascript
const wrapper = shallowMount(CoreGame, options);

await Vue.nextTick();
console.log("[test]" + wrapper.vm.loading);
expect(wrapper.vm.loading).to.equal(false); // why is this getting the outdated value??? <---- FAILED ASSERTION
```

Basically, I was confused as to why the `loading` field was obtaining an older value (`false`) while according to the `finally` block (which in my head, runs before all the tests were run), it should have been `true`. But... when I ran this and looked at the console logs, I see otherwise.

```
[CoreGame]true
[test]true <--- on test, which causes assertion to fail, because I am expecting a false
[fx]false <--- on finally block, the result I want
```
The test was running before the `finally` block! I'm not sure how, but I am guessing `await Vue.nextTick();` only ensures the code in the `catch` block finishes running, but does not ensure the `finally` block to be run?

Maybe there is something I am missing. Thanks for your help guys!

**Comment by susanBuck** [comment]
Hi @ihimawan - I'd like to run your code to test it. Can you tell me which directory in your e28 repo you're working in? I see a `p4` but also a `p4-0` so want to make sure I'm in the right place.

**Comment by ihimawan** [comment]
@susanBuck thanks! it would be `p4`! And the test is called `CoreGame.spec.js` under `tests/unit`. `p4-0` was experimental.. so can just ignore that : )

**Comment by susanBuck** [comment]
Cool - checking it out now. : )

**Comment by susanBuck** [comment]
In debugging your problem, I tried the solution in this post:
https://github.com/vuejs/vue-test-utils/issues/83#issuecomment-471840420:

```.js
await new Promise(resolve => setTimeout(resolve));
```

![image](https://user-images.githubusercontent.com/237711/70456313-e5632100-1a7b-11ea-9626-043bf8b7c7c6.png)

That did the trick:
![image](https://user-images.githubusercontent.com/237711/70456351-f2801000-1a7b-11ea-9f1a-19816699364c.png)


Also, FYI, this assertion should be updated to expect `Error` (capital E) in order to pass:
```
expect(wrapper.text()).to.include("error");
```

**Comment by ihimawan** [comment]
`await new Promise(resolve => setTimeout(resolve));` does that essentially just flush what's existing because if the `setTimeout` runs, it means the promises before it had all been resolved?

**Comment by susanBuck** [comment]
np!

And yup, that's my interpretation of what it's doing.

**Comment by ihimawan** [comment]
Awesome, thanks so much 👍

**Comment by susanBuck** [comment]
Check out this guide: https://vue-test-utils.vuejs.org/guides/testing-async-components.html

It does a good job of explaining the different techniques.

This paragraph, specifically, explains why setTimeout does the trick:

> The reason setTimeout allows the test to pass is because the microtask queue where promise callbacks are processed runs before the task queue, where setTimeout callbacks are processed. This means by the time the setTimeout callback runs, any promise callbacks on the microtask queue will have been executed. $nextTick on the other hand schedules a microtask, but since the microtask queue is processed first-in-first-out that also guarantees the promise callback has been executed by the time the assertion is made

**Comment by ihimawan** [comment]
```
$nextTick on the other hand schedules a microtask, but since the microtask queue is processed first-in-first-out that also guarantees the promise callback has been executed by the time the assertion is made
```
I mean, this kind of just makes it sound like they're attempting to do the same thing, making sure the promises are finished first. But nothing specific about catch / finally blocks. Maybe I need to do some more research into how catch / finally blocks are being executed in regards to promises.

**Comment by ihimawan** [comment]
sorry! i accidentally closed it.

**Comment by susanBuck** [comment]
You're right, it does sound like they're doing the same thing. That paragraph I quoted is such a mouthful, I misinterpreted it in my first pass. : )

I just spent some time poking at this again, and found that if you do await nextTick **twice**, it will work:

```js
await wrapper.vm.$nextTick()
await wrapper.vm.$nextTick()

expect(wrapper.vm.loading).to.equal(false);  # PASSES
```

In trying to wrap my head around this, I added some console.logs in the test. Here are the relevant parts:

```js
console.log('Test: shallowMount component');
const wrapper = shallowMount(CoreGame, {
    localVue,
    store: storeFailedFetch
});

// We know this works; trying to get it work with nextTick as well
//await new Promise(resolve => setTimeout(resolve)); 

console.log('Test: Before 1st await nextTick');
await wrapper.vm.$nextTick()

console.log('Test: Before 2nd await nextTick');
await wrapper.vm.$nextTick()

console.log('Test: expect loading to equal false');
expect(wrapper.vm.loading).to.equal(false);
```

I also added some console.logs in the component (again, sharing just the relevant parts here):

```js
this.$store
  .dispatch('setProfileCollections')
  .then(() => {
      this.startGame();
      console.log('Component: then');
  })
  .catch(() => {
      this.error = true;
      console.log('Component: catch');
  })
  .finally(() => {
      this.loading = false;
      console.log(
          'Component: finally (where loading is set to false)'
      );
  });
```

Here's the output when run:

```
Test: shallowMount component
Test: Before 1st await nextTick
Component: catch
Test: Before 2nd await nextTick
Component: finally (where loading is set to false)
Test: expect loading to equal false
```

Notice how the 1st nextTick console is triggered before the `catch`, and the 2nd nextTick console is triggered before the `finally` (where loading is set to false).

Because [then/catch/finally are microtasks.](https://javascript.info/microtask-queue) and [nextTick is also a microtask](https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd), this makes sense that we need two nextTicks before the code in the `finally` is triggered.

`setTimeout`, however, is a *macro* task and it runs after microtasks, which is why the `await new Promise(resolve => setTimeout(resolve));` approach worked.

At least, that's my takeaway from the paragraph I shared above. : )
