### ISSUE TITLE
moderate severity security alert on github: serialize-javascript

### ISSUE THREAD

**Issue by fergus588** [susanBuck/e28-fall19#169]
I have a moderate severity security alert on github something about REGEX which i don't have in any of my projects, is this something important?
![image](https://user-images.githubusercontent.com/55098964/70727633-e2746480-1cf7-11ea-9f04-d1ed9627a0a4.png)

**Comment by apatruno618** [comment]
I have the same thing starting from p2
![Screen Shot 2019-12-12 at 12 02 36 PM](https://user-images.githubusercontent.com/35854109/70732942-581c0880-1cd7-11ea-9a6d-ed72dfc2c248.png)

**Comment by rokmesojedec** [comment]
just remove the references from your project and recompile. Works for me.

**Comment by susanBuck** [comment]
`serialize-javascript` is a dependency of our dependencies, `"@vue/cli-plugin-babel"` and `@vue/cli-service@4.0.5`. We can't remove these latter dependencies without sacrificing functionality we're utilizing with vue cli.

For reference, here's how we can see which dependencies are using `serialize-javascript`:

```
/Applications/XAMPP/xamppfiles/htdocs/e28/zipfoods (master) ! $ npm list serialize-javascript
zipfoods@0.1.0 /Applications/XAMPP/xamppfiles/htdocs/e28/zipfoods
├─┬ @vue/cli-plugin-babel@4.0.5
│ └─┬ webpack@4.41.2
│   └─┬ terser-webpack-plugin@1.4.1
│     └── serialize-javascript@1.9.1  deduped
└─┬ @vue/cli-service@4.0.5
  ├─┬ copy-webpack-plugin@5.0.4
  │ └── serialize-javascript@1.9.1 
  └─┬ terser-webpack-plugin@2.2.1
    └── serialize-javascript@2.1.0 
```

What needs to happen is `vue/cli-plugin-babel` and `vue/cli-service` need to address *their* code to update `serialize-javascript`. 

This means waiting on those developers to fix the issue (or until they get and accept a pull request to fix the issue by someone in the community).

Until that happens, though, we don't need to be concerned because the impacted dependencies are listed under our `devDependencies` in `package.json` - which means that vulnerable code is not actually being run on production where a XSS attack could cause harm.
