### ISSUE TITLE
Apache SPA routing

### ISSUE THREAD

**Issue by extra808** [susanBuck/e28-fall19#173]
I thought I had handled the SPA routing with Apache server for P3 but apparently it was just Firefox caching pages. Like [Teri](/susanBuck/e28-fall19/issues/147#issuecomment-565753978), [the instructions](https://hesweb.dev/e28/notes#/vue/build-comprehensive?jump=preparing-to-deploy-to-digitalocean) are not working for me. `sudo a2enmod rewrite` says the module is already enabled, `AllowOverride All` is in my virtual host directory configuration, I put the .htaccess file in public/ and re-ran `npm install` and `npm run build` so it's in dist/ but it's not working.

Does it matter that all my links are deeper than one level? They're all either like this `/techniques/0/orientation` or this `/techniques/css`.

I should be more specific: the Back button works in all browsers to return from one page on the site to the previous page on the site. What doesn't work is using a link that goes to another site then clicking back or copying a deep link from the site and trying to go directly to it in a separate window/tab.

**Comment by naztronaut** [comment]
I responded with this in the other thread, see if this works:

> Try putting the .htaccess in your `/var/www/html` directory - the permissions should cascade down. I mine in my root and the contents are:
> 
> ```
> <IfModule mod_rewrite.c>
>   RewriteEngine On
>       RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
>       RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
>       RewriteRule ^ - [L]
>   RewriteRule ^ /index.html
> </IfModule>
> ```
> 
> It's a tiny bit different from what's done in the classnotes but the rewrite rules are pretty much the same.
> 
> Enabling mod_rewrite and restarting apache are global actions so you can do those from any directory.

**Comment by susanBuck** [comment]
Hi @extra808 -

Are you creating the `.htaccess` file directly on the server? I ask because I'm not seeing it in your repository under [p3/public](https://github.com/extra808/e28/tree/master/p3/public).

And just to be clear that we're on the same page/testing the same thing, a link we might test for this is <https://p3.dgmde28.cognize.org/techniques/css> yes? 

_re: deeper than one level_ - that shouldn't impact things - case in point, here's a link on zipfoods:
<http://e28-zipfoods.hesweb.xyz/product/driscolls-strawberries> that works when I visit it directly.

**Comment by susanBuck** [comment]
@extra808 Because this is a production-specific thing, would you mind sharing access to your server with me so I can take a look?

If so, instructions here: https://hesweb.dev/e28/notes#/appendix/instructor-server-access

**Comment by extra808** [comment]
Yes, I created .htaccess on the production server (I had originally put it inside an Apache .conf file, before the .htaccess suggestion was made). Yes, a PostsList route like https://p3.dgmde28.cognize.org/techniques/css or a PostPage route like https://p3.dgmde28.cognize.org/techniques/0/orientation.

Thank you, I've added your key on the server. I normally SSH using the original hostname, dwa15.cognize.org but I assume they all work. The P3 folder is `/var/www/dgmde28/e28/p3/`. Note it's set up to use Let's Encrypt so you'll see signs of that in `/etc/apache2/sites-enabled/`.

**Comment by susanBuck** [comment]
Found the problem...

In `/etc/apache2/sites-enabled/730-p3.dgmde28-le-ssl.conf` there was an error in the Directory path. 

This line:
```
<Directory "/var/www/dwa15/dgmde28/e28/p3/dist">
```

Needed to be:
```
<Directory "/var/www/dgmde28/e28/p3/dist">
```

I found the error because I noted that the routing was working when accessing the site via `http` instead of `https`. Knowing that, I compared `730-p3.dgmde28.conf` (working) line by line with `730-p3.dgmde28-le-ssl.conf` (non-working) until I spotted the difference/problem.

**Comment by susanBuck** [comment]
Additional note: the reason it was breaking it is because with the path wrong, the necessary `AllowOverride All` was not being read.

```
<Directory "/var/www/dwa15/dgmde28/e28/p3/dist">
    AllowOverride All
</Directory>
```

And without `AllowOverride All`, the project-specific `.htaccess` file wasn't being read.

**Comment by extra808** [comment]
D'oh, thanks! It's working, now that the correct path, /var/www/dgmde28/e28/p3/dist, is used everywhere in both the SSL and non-SSL .conf files.
