### ISSUE TITLE
Is this a reasonable use of setTimeout in Mocha?

### ISSUE THREAD

**Issue by terichadbourne** [susanBuck/e28-fall19#177]
I'm trying to unit test a component in Mocha by passing it a `people` array that under normal circumstances would be pulled from Axios. There's a `v-else` on the page that displays "Loading records..." if `people` doesn't exist, and that usually flashes for less than a second when the page first loads before it pulls the records. 

In Mocha, my tests were failing because they were looking for whatever people data I asked them to find in the string "Loading records." I would have expected that `people` would already be the value I passed in via `propsData` in the text and that it would have loaded immediately. ¯\_(ツ)_/¯ 

I tried these things which didn't help: 
- using a computed method for `people` as shown in @susanbuck's ProductsPage example (same result as before, still sees the loading message)
- using `await new Promise(resolve => setTimeout(resolve));` as seen in another student's timing issue (failed because I wasn't using it in an async function)

I then reverted to a plain old `setTimeout`, which is working. It feels hacky to me, so just wanted to check and see if there are cleaner ways to solve this before leaving it as my solution. 

The commit with my now-passing-but-somewhat-hacky unit test is [here](https://github.com/terichadbourne/e28/commit/6d40d044146dfc54bf0aa58dc2c93c7b4ef10f29), with commented out portions showing the other things I tried. Suggestions welcome!

**Comment by susanBuck** [comment]
FYI Looking at this now. Will reply shortly! Sorry for the delayed response - my other class has their final due date today so I've been swamped with their last minute questions. : )

**Comment by susanBuck** [comment]
Your solutions gets the test to pass, but as you suspected, it doesn't feel quite right.

Waiting for an axios call to finish is something we would expect more of in an E2E test.

In a Unit test, we want to mock the axios data so that we can focus on testing the component itself.

Let's talk about the couple different approaches you took to address this...

First, I saw an attempt with `propsData`:

```js
 const wrapper = shallowMount(People, {
      propsData: { people }
}
```

The People Component does have a [**data option**](https://vuejs.org/v2/api/#data) of `people`, but it does not have a [**props option**](https://vuejs.org/v2/api/#props) of `people`. Because of this, setting `propsData` when mounting did not have the effects you were expecting.

Next, I saw you tried mounting with a computed property of `people`:

```js
const wrapper = shallowMount(People, {
    computed: {
        people: function () {
            return [people]
         }
     }
})
```

This won't work because there is already a `people` data option, so it produces this error:

```
[Vue warn]: The computed property "people" is already defined in data.
```

With those two approaches eliminated - the question remains then of **how we can pass in a data option?**

For this, we can turn to the [wrapper's `setData` method](https://vue-test-utils.vuejs.org/api/wrapper/#setdata).

Example:
```js
wrapper.setData({ people: people })
```

Using that technique, I simplified your test to confirm that each person's name was being displayed. The idea here was to start simple, then add complexity to the test once I knew it was working. I also added the _RouterLinkStub_; without it I was getting a warning *Unknown custom element: <router-link>*.

Here's the simplified test:

```js
/* eslint-disable no-console, no-undef, no-unused-vars */

import { expect } from 'chai'
import { shallowMount, RouterLinkStub } from '@vue/test-utils'
import People from '@/components/pages/People.vue'

describe('People.vue', () => {

    it('displays multiple people with name and any existing feedback', () => {

        // Define people data for testing
        let people = [
            {
                "id": 1,
                "name": "Janet",
                "rave": "The people here are awesome.",
                "rant": "Bureacracy is painful. :("
            },
            {
                "id": 2,
                "name": "Theodore",
                "rant": "I don't get enough time to code."
            }
        ]

        // Mount our component
        const wrapper = shallowMount(People, {
            stubs: {
                RouterLink: RouterLinkStub
            }
        })

       // Set the data option of `people` to our hard-coded `people` data
        wrapper.setData({ people: people })

        // Assert our results
        expect(wrapper.text()).to.include('People')

        // Assert each person is showing
        people.forEach((person, index) => {
            expect(wrapper.text()).to.include(people[0].name)
        })
    })
})
```

And here it is passing:

![image](https://user-images.githubusercontent.com/237711/71043534-e8ee4c00-20fc-11ea-8686-6932135eed45.png)

With that simplified version passing, I brought back the other expectations in your test:

```js
people.forEach((person, index) => {
            people.forEach((person, index) => {
                expect(wrapper.text()).to.include(people[0].name)
                if (people[index].hasOwnProperty('rave')) {
                    let foundRaveLink = wrapper.find('[data-test="rave-link"]').exists();
                    expect(foundRaveLink).to.equal(true);
                    expect(foundRaveLink.text()).to.include(people[index].rave)
                }
                if (people[index].hasOwnProperty('rant')) {
                    let foundRantLink = wrapper.find('[data-test="rant-link"]').exists();
                    expect(foundRantLink).to.equal(true);
                    expect(foundRantLink.text()).to.include(people[index].rant)
                }
            })
        })
```

This caused the tests to fail:

```
TypeError: foundRaveLink.text is not a function
```

To understand the problem, read the following lines of code I added comments to:

```js
// This gets a boolean value true/false as to whether the rave link is found
let foundRaveLink = wrapper.find('[data-test="rave-link"]').exists();

// This confirms it was true (found)
expect(foundRaveLink).to.equal(true);

// This is the problem... Recall that foundRaveLink is a boolean value, so you can't do foundRaveLink.text() here.
expect(foundRaveLink.text()).to.include(people[index].rave)
```

To address the above problem, we might refactor to something like this:

```js
// Get the link itself
let raveLink = wrapper.find('[data-test="rave-link"]');

// Confirm the link exists
expect(raveLink.exists()).to.equal(true);

// Confirm the link contains the text we want
expect(raveLink.text()).to.include(people[index].rave)
```

This will still fail though, because the [wrapper find method](https://vue-test-utils.vuejs.org/api/wrapper/#find) gets us the *first* element matching our, but our tests is checking for multiple people.

To address this, I suggest giving each link a more specific selector, e.g.:

```js
<router-link
    :data-test='"rave-link-" + person.id '
    :to='{ name: "rave", params: {"id" : person.id }}'
>{{ person.rave }}</router-link>

<!-- DO THE SAME THING FOR THE RANT LINK -->
```

Now the link will have an attribute `data-test` set to `rave-link-[id]`.

And we can rewrite our tests as follows:

```js
people.forEach((person, index) => {
    people.forEach((person, index) => {
        expect(wrapper.text()).to.include(people[index].name)
        if (people[index].hasOwnProperty('rave')) {
            // Find the specific link for this specific person
            let raveLink = wrapper.find('[data-test="rave-link-' + people[index].id + '"]');

            // Assert the link exists
            expect(raveLink.exists()).to.equal(true);

            // Assert the link has the text we want
            expect(raveLink.text()).to.include(people[index].rave)
        }
        if (people[index].hasOwnProperty('rant')) {
            let rantLink = wrapper.find('[data-test="rant-link-' + people[index].id + '"]');
            expect(rantLink.exists()).to.equal(true);
            expect(rantLink.text()).to.include(people[index].rant)
        }
    })
})
```

And here it is passing: 
![image](https://user-images.githubusercontent.com/237711/71044598-138dd400-2100-11ea-8fd0-f1eacadfef09.png)

Let me know if you have any questions about the above changes/walk-through!

**Comment by terichadbourne** [comment]
Thank you so much for the detailed step-by-step feedback @susanBuck! Super clear and very helpful. I have this working now with the approach you suggested.
