### ISSUE TITLE
Clarity of Question 6 for Assignment #3

### ISSUE THREAD

**Issue by cgloge** [susanBuck/e28-fall19#32]
Hi there,

I might be overthinking things a bit in terms of what qualifies as "rendering" HTML so I'm a bit confused on how to answer this one. I believe the Week 3, Part 2 lecture covers this, but I feel that cloaking makes the answer a bit ambiguous.

Could you give more guidance on how to think about the answer to this question?

P.S. Sorry for being a bit vague... Trying to not give the answer here. :)

Best,
Carly

**Comment by cgloge** [comment]
Ah... I think I got the answer now after watching more of the lectures. :)

**Comment by mourad1974** [comment]
Watching the lectures one more time after reading the questions will help a lot, and try focus on the lecture that talk about the subject to minimize time. :)

**Comment by susanBuck** [comment]
Glad it got cleared up.  : )

Just a reminder that when you have questions from the Content Check portion of the assignments to email those questions to me directly:

![image](https://user-images.githubusercontent.com/237711/65440267-75d38300-ddf6-11e9-929b-d284ae603e88.png)

I have this policy in place because I've had experiences in the past where students have inadvertently given away the answer, or too much of a hint, to the rest of the class. This has happened in the original post/question, and also in replies from classmates. 

Never hesitate to email me directly (susanbuck@fas.harvard.edu) with these sorts of questions - always happy to clarify.
