### ISSUE TITLE
Question 5 for Assignment #3

### ISSUE THREAD

**Issue by claudiomanuelboston** [susanBuck/e28-fall19#33]
Susan,
I think you mean browser instead of ".. Brower's DOM API.."?

**Comment by ihimawan** [comment]
I think the the `Browser's DOM API` is what she meant by the real DOM instead of the Virtual DOM.

**Comment by susanBuck** [comment]
Just a reminder that when you have questions from the Content Check portion of the assignments to email those questions to me directly:

![image](https://user-images.githubusercontent.com/237711/65440267-75d38300-ddf6-11e9-929b-d284ae603e88.png)

I have this policy in place because I've had experiences in the past where students have inadvertently given away the answer, or too much of a hint, to the rest of the class. This has happened in the original post/question, and also in replies from classmates. 

Never hesitate to email me directly (susanbuck@fas.harvard.edu) with these sorts of questions - always happy to clarify.
