### ISSUE TITLE
FYI template element browser support

### ISSUE THREAD

**Issue by extra808** [susanBuck/e28-fall19#42]
Support for the `<template>` element is not universal, most notably it's [not supported by any version of Internet Explorer](https://caniuse.com/#feat=template). In browsers that don't support it, the elements within `<template>` will be rendered on page load, though that can be hidden with CSS:
```CSS
template {
	display: none;
}
```

I wondered if this was relevant for Vue projects, if there were browsers that don't support `<template>` but are supported by Vue; there are. [Vue.js supports all ECMAScript 5 browsers](https://vuejs.org/v2/guide/installation.html#Compatibility-Note), which includes IE9+ and Opera Mini.

There are polyfills, JavaScript code to add support for features in browsers that don't support them natively, but there can still be problems caused by the browser's initial rendering of the `<template>` contents.

**Comment by susanBuck** [comment]
Good points. If your app needs to support IE users, I'd avoid the template element. 

That being said, according to [statcounter.com IE accounts for 2.19% of browsers in the world market](https://gs.statcounter.com/browser-version-partially-combined-market-share#monthly-201808-201908-bar). This number might be even less depending on the market your site serves. Web traffic analytics can give you the best insight into what software your audience is using. 

Most use of IE now-a-days is for legacy support of internal enterprise applications. Think: a small hospital whose internal software is old and only functions on IE, but they don't have the resources to update.

My recommended approach to obsolete browsers ([which IE is](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732)) is to detect when users enter via them and show them a message like this: <https://www.lynda.com/upgrade-browser>.

This way you get to focus your resources on the browsers the majority of your users are using, and you also help educate visitors on updating their outdated and often security-flawed browsers.

I don't think the point of your post was to make an argument for supporting IE - I think you're just pointing out the discrepancy in the support of <template> vs. Vue's support of ECMAScript 5 browsers. 

However, I just wanted to share the above info in case any students are wondering why/if they should be supporting IE. : )

**Comment by kreinholz** [comment]
Excellent point, @extra808! Internet Explorer has been going the way of the Dodo for a while now, but IE compatibility issues still seem to come up every now and then. On my Windows 10 machine, Edge is the new default browser (although I use Chrome), so even Microsoft seems to be urging people to migrate from IE. That having been said, at work we still use IE extensively, and sadly, we're a large government agency. But the reason is exactly as @susanBuck said--tons of legacy web applications that for reasons us 2019 folks can only scratch our heads at, only support IE.

Personally, I like to test my web apps on Chrome and Firefox, and sometimes Safari (especially mobile Safari on my iPhone). Good to know we don't need to support IE! (Especially when you go back to really painful versions like 8 or 9).
