### ISSUE TITLE
Getting Access Denied when using localhost

### ISSUE THREAD

**Issue by gpunzalan18** [susanBuck/e28-fall19#49]
I added the virtual host entries for all the subdirectories for `e28` (i.e. `p1`). So I am able to access them using `.loc` extension (i.e. `p1.loc`). But I also tried to access them using the path `localhost/e28/<foldername>` and I am getting access denied. This is the message displayed on the page:

> You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.
> If you think this is a server error, please contact the webmaster.

But when I comment out `Include etc/extra/httpd-vhosts.conf` from `/Applications/XAMPP/xamppfiles/etc/httpd.conf`, hitting the subdirectories via the localhost path works fine. 

Could someone explain why this is happening? Would I just need to change permission on my files so I can access them both ways?

**Comment by tedsirota** [comment]
Running into the same exact problem. Not sure what happened since everything was running fine for the past week. Commenting `Include etc/extra/httpd-vhosts.conf` fixes access to the subdirectories for me as well.

**Comment by cgloge** [comment]
This solved the issue for me on my Mac:

https://www.digitalocean.com/community/questions/permission-denied-after-creating-droplet-using-ssh-keys

**Comment by susanBuck** [comment]
Check out ["Fixing http://localhost" in the Local domain note set](https://hesweb.dev/e28/notes#/local-server/local-domains?jump=fixing-codehttplocalhostcode)

I believe that'll address the issue you're describing, but if not, let me know.

**Comment by spttruong** [comment]
I had a very similar issue last week after setting up local domains for some reason. Along with trying the solutions provided above, what worked for me was manually checking/changing permissions on my e28 folder or subdirectories.

On Mac: Secondary click the file or directory > Get Info > Sharing and Permissions > Change read/write permissions

On Windows: Right click the file or directory > Properties > Go to the 'Security' tab > modify/add/remove permissions

**Comment by kreinholz** [comment]
I found setup to be a bit finicky, but on a vanilla XAMPP installation on Windows 10 using the [course-provided download link](https://hesweb.dev/e28/notes#/local-server/xampp-windows), and following all course instructions to the letter (and squashing some typos I inadvertently inserted while trying to manually retype rather than copy+paste), everything worked fine. I can confirm all virtual domains work beautifully on my Windows 10 machine (and on my Digital Ocean production server).

There was some helpful information on this in an [earlier thread](https://github.com/susanBuck/e28-fall19/issues/29#issuecomment-534180768).

**Comment by gpunzalan18** [comment]
Thank you all! 

@tedsirota --- I followed the notes from @susanBuck and am now able to access both ways!
