### ISSUE TITLE
Questions on Project 1 Submission

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#64]
I just submitted Project 1, but it's not giving me the option to re-take/submit the quiz again (I wanted to check all the links, etc). Along those lines, I needed to add a little documentation to the code itself. Is there a "documenting standard" that's expected for inline code? 

Thanks

**Comment by susanBuck** [comment]
I just toggled on the "Multiple-attempts" and "Let Students See Their Quiz Responses" options.

FYI I checked on my end and all the links you submitted appear correct/working.

Also FYI, I'd consider adding/cleaning up documentation to fall under the category of "minor commits" as described here: [Work & Grading : Projects](https://hesweb.dev/e28/work-and-grading#Projects). Because of this you don't have to re-submit after making changes along those lines. You're welcome to, but it's not necessary.

No set documenting standard expected for inline code.

**Comment by gaderrick** [comment]
One more question- I added some documentation to the script.js file. Do I need to update the project submission that has the historical hash reference? None of the code lines changed.

**Comment by susanBuck** [comment]
Nope, no need to update submission.

**Comment by coinshot** [comment]
@susanBuck mentioned that the "Let Students See Their Quiz Responses" is activated, I am not finding any option for than on my Canvas to check my submitted quiz responses and double-check them, would someone please let me know how I will be able to do so?
