### ISSUE TITLE
DNS issue with subdomain

### ISSUE THREAD

**Issue by atanasgizdov** [susanBuck/e28-fall19#66]
Anyone else having trouble with getting DNS to resolve their subdomain? I may also be missing something so I have attached my DNS setup in screenshots below. I am using the base Apache conf file (before making changes to redirect subdomain requests) so both should resolve to the core path but the subdomain is not. I've let it settle on the Namecheap DNS side for 2-3 hours now and no luck. I tried both the wildcard and exact match subdomains on Namecheap

Anyone else have this issue?

![image](https://user-images.githubusercontent.com/16026956/66531104-9c710980-ead8-11e9-9333-bdf67fa8d43f.png)

![image](https://user-images.githubusercontent.com/16026956/66531162-d5a97980-ead8-11e9-86a3-d23f9e3ba38f.png)

**Comment by naztronaut** [comment]
Services like Digital Ocean and AWS block pings by default. You need to tell the firewall to allow ICMP traffic. I never remember how to do anything in iptables but a quick google on "icmp allow" led me to this page: https://www.crybit.com/iptables-rules-for-icmp/

And the relevant commands to run are:

```
iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT
```

**Comment by susanBuck** [comment]
In your ping test, it's pinging IP 92.242.140.21 then timing out.

In my ping test it's returning *ping: cannot resolve project1.naskogizdov.com: Unknown host*

![image](https://user-images.githubusercontent.com/237711/66532694-38514400-eade-11e9-930e-9726c419cf81.png)

Curious if you made any changes since posting this thread?

**Comment by susanBuck** [comment]
@naztronaut Hmm - I'm able to ping my DigitalOcean server, and have not messed with the IP table settings.

**Comment by naztronaut** [comment]
@susanBuck Strange! 

I also **just** realized DO allows you to configure firewall settings from their control panel, like AWS does (never noticed before, would have made my life easier with my other projects). Maybe you have ICMP inbound enabled:

![image](https://user-images.githubusercontent.com/8021112/66532964-405db380-eadf-11e9-88c2-c267ce80aac7.png)

Mine is currently not active so I can't ping. 

I'd also recommend using nslookup to see where the domain is pointing to:

![image](https://user-images.githubusercontent.com/8021112/66532984-58cdce00-eadf-11e9-8571-79a52a31294f.png)

I have both sub and sub-sub domains set up pointing to the same server without issues. But I can't ping because ICMP is not open.

**Comment by susanBuck** [comment]
Good call on `nslookup`, @naztronaut:

```
/Applications/XAMPP/xamppfiles/htdocs   $ nslookup naskogizdov.com
Server:		208.59.247.45
Address:	208.59.247.45#53

Non-authoritative answer:
Name:	naskogizdov.com
Address: 162.255.119.231
Name:	naskogizdov.com
Address: 159.65.239.116
```

Note how it's resolving to two different IP addresses.

Also, now when I ping naskogizdov.com it resolves to `162.255.119.231` while earlier it was resolving to `159.65.239.116`.

@atanasgizdov Any chance you have DNS settings for this domain via some other domain service?

**Comment by atanasgizdov** [comment]
@ susanBuck No I just registered for this domain so I have no idea why it's resolving to two domains. I just did another nslookup this morning, after not having touched the settings from yesterday and it's still resolving to three different domains and I have no idea why. The 159 address is the one that Digital ocean provides for my droplet. It looks like it's also resolving my subdomain to a third address

```
bos-mp1ma:~ agizdov$ nslookup project1.naskogizdov.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	project1.naskogizdov.com
Address: 92.242.140.21

bos-mp1ma:~ agizdov$ nslookup naskogizdov.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	naskogizdov.com
Address: 162.255.119.231
Name:	naskogizdov.com
Address: 159.65.239.116

bos-mp1ma:~ agizdov$ 
```

![image](https://user-images.githubusercontent.com/16026956/66574368-18ec0280-eb42-11e9-9e09-ed8b76b08f3c.png)

Conf file: 
```
 root@VueJSFall2019:~# vim /etc/apache2/sites-enabled/000-default.conf 
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        <Directory /var/www/html/>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
        </IfModule>

</VirtualHost> 
```

**Comment by susanBuck** [comment]
@atanasgizdov Can you change the CNAME Host to wildcard `*` instead of Project 1?

I don't think using `project1` as the CNAME is the root cause of the problem, and I know you said in your initial thread you tried the wildcard already, but lets just give it another shot.

Also, can you share a screenshot of your domain settings. Specifically we should double check the domain is actually using Namecheap's nameservers and no redirects are set up.

![image](https://user-images.githubusercontent.com/237711/66584049-68d2c580-eb52-11e9-811c-146e66e006f0.png)

**Comment by susanBuck** [comment]
Checking in on this, looks like `http://project1.naskogizdov.com` and `http://naskogizdov.com` are both functioning.

Curious if you changed something or if it just started working?

**Comment by atanasgizdov** [comment]
Thanks for checking in - I changed to the wildcard as you suggested. I think triggering another DNS flush ended up solving it as 1m later, both domains started working correctly. I still have no idea what IP addresses it was referring to before but they both seem to be working correctly now.
