### ISSUE TITLE
Double-check responses after submission

### ISSUE THREAD

**Issue by coinshot** [susanBuck/e28-fall19#72]
@susanBuck mentioned that the "Let Students See Their Quiz Responses" is activated, I am not finding any option on my Canvas to check my submitted quiz responses and double-check them, would someone please let me know how I will be able to do so?

**Comment by susanBuck** [comment]
Hi @coinshot - 
That option doesn't exist for regular weekly assignments, just the project submissions.

Can you let me know which assignment you're trying to double check?

**Comment by coinshot** [comment]
@susanBuck Not any specific project, I was just hoping to be able to do this on weekly assignments in general, sometimes a double check on your previous responses on a different day with a fresh mind will reveal your dumb mistakes, but no worries, thank you.

**Comment by susanBuck** [comment]
I wish there was a way to let students go back and double check/amend answers, but the only option I have is this: 

![image](https://user-images.githubusercontent.com/237711/66687052-60ac8000-ec4f-11e9-8d3f-b727f6939378.png)

The silly part about this setting is that while it won't show students the correct answers (until I unlock them), it will show students what questions they got incorrect. Using this info, a student could then re-submit their assignment with amended answers.

One thing you could do is make a copy of your submission right before you submit. 

There's a Chrome plugin called "Full Page Screen Capture" that lets you take full page screencaptures and save as PDFs.

Or you could copy the questions and answers in your own notes. That could be useful in general as reference because you could make notes to yourself about why you answered a question the way you did.

Then, later if you reviewed this info and found you wanted to change an answer, you could re-submit a new assignment.

It's hacky and not ideal, I know, but it's the best workaround I can think of given Canvas' current options.

**Comment by coinshot** [comment]
That is a good approach, I will do that from here on out, thank you, @susanBuck .
