### ISSUE TITLE
Double-check Projects after submission

### ISSUE THREAD

**Issue by extra808** [susanBuck/e28-fall19#73]
When I look at [Project 1](https://canvas.harvard.edu/courses/63162/quizzes/156412), I can't see what I submitted, there's only the "Take the Quiz Again" links, which I don't want to click in case that would destroy what I've already submitted. 

> Hi @coinshot - 
> That option doesn't exist for regular weekly assignments, just the project submissions.

> Can you let me know which assignment you're trying to double check?

_Originally posted by @susanBuck in https://github.com/susanBuck/e28-fall19/issues/72#issuecomment-541160040_

**Comment by susanBuck** [comment]
This originally came up in issue #64 -

I said I toggled on "Let Students See Their Quiz Responses"

I misinterpreted this as meaning it would let you all go back and see a previous attempt.

It turns out it just means you can see your answers immediately after you submit.

So there is no way to see the assignments after they're submitted. 

If you have concerns about your Project 1 submission, email me.

**Comment by coinshot** [comment]
Just a quick update, I called Canvas folks and submitted this as a feature request, we might get it in the future.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
