### ISSUE TITLE
Our Domain Name

### ISSUE THREAD

**Issue by audreychenjj-2019** [susanBuck/e28-fall19#76]
I'm curious why we use p1.domain instead of domain/p1 as our production link?

**Comment by susanBuck** [comment]
Hi @audreychenjj-2019 - We do this to simulate how applications are setup and run in the real world - via their own domain, with their own document root. 

Consider a line like this:
```html
<script src='/js/scripts.js'></script>
```

If we were running our application at `http://domain.com/p1` then the path `/js/scripts.js` would actually point to the document root for domain.com (`/`, not `/p1/`), and it would fail to load. 

To address this, we'd have to start including the application path in the includes:
```html
<script src='/p1/js/scripts.js'></script>
```

Or use relative paths:
```html
<script src='js/scripts.js'></script>
```

Neither of these things are things we'd want to do with a "real" application deployed to its own domain. 

So to avoid this, we just run the projects as their own document roots, so we can use the kind of paths/setup we'd use in the real world.

And we use subdomains so we can have individual addresses for each project without having to create multiple domains.

**Comment by audreychenjj-2019** [comment]
I guess I'm still thinking about Susan's comments. Why most of the websites use domain/p1 format then? For example https://github.com/susanBuck/e28-fall19/issues/

**Comment by extra808** [comment]
> Why most of the websites use domain/p1 format then?

In this class, "the website" is not everything you produce for the classes, each project should be thought of and presented on its own, with its own resources like image files, CSS files, etc.; each project is **the** website until it's completed. 

GitHub isn't a very typical site but for comparison, GitHub.com is "the website," the application, not GitHub.com/susanBuck/. , The GitHub.com/susanBuck/ URL represents one user of the website. We're going to learn how to use URLs within our Vue applications, say to give each game player their own URL where their high scores are listed, we just haven't gotten to that part yet.

**Comment by susanBuck** [comment]
@extra808 is correct - eventually our individual applications in this course will evolve so that they have multiple "pages" and we will start to see expanded paths like `http://example.yourdomain.com/contact` or `http://example.domain.com/user/susanBuck`

Specifically, we'll see that in week 9 when we cover *Single-Page Applications (SPA) w/ Vue router*.

So far, though, our individual applications have only involved one "page" so we haven't needed expanded paths beyond things like `http://p1.loc`(local) / `http://p1.yourdomain.com` (production).

One way to understand this better is to imagine you're a web developer and each individual project/application you create in this course is a project/application for a completely different company. 

You wouldn't want to deliver the final product with URLs like this:

http://domain.com/companyA/
http://domain.com/companyB/

Instead, you'd deliver:

http://companyA.com
http://companyB.com

But I don't want you to have to actually create separate domains for each project, so we simulate this with subdomains:

http://companyA.domain.com
http://companyB.domain.com

**Comment by audreychenjj-2019** [comment]
I think I finally got it. Thank you!
