### ISSUE TITLE
p2 and components

### ISSUE THREAD

**Issue by pausman** [susanBuck/e28-fall19#77]
Are there 'good' parts of our games that should be made into a component? When I look at my game I do not really see any part that would be repeatable.  Should I add functionality to create a need or just use the component techniques (data, props, events, etc) without thinking about that issue?

Thanks,
Pat

**Comment by susanBuck** [comment]
Finding a place where you *need* a component might not exist in some projects, especially given the relatively small scale of these games.

If that's the case - it's up to you.

You can component-ize some portion(s) of your game. Even if it feels unnecessary because it's not something that needs to repeat - it's just about practice right now. 

For example, in your game (Prisoner's Dilemma) maybe you have a `<intro-screen>` and a `<game-screen>` component. The `<game-screen>` component could have child components of `<verdict-figure>`. 

Or you could add functionality that you feel would better warrant component(s). Maybe a `<game-results>` component that displays the results of the game (similar to the lecture example).

Or you could come up with a new game that you think would better benefit from components.

**Comment by susanBuck** [comment]
I'm re-opening this thread because I discuss it in the Week 8 lecture videos, so I want it to be easily findable. : )

**Comment by kreinholz** [comment]
I have a similar question. The [week 8 example](https://github.com/susanBuck/e28/blob/master/week8spa/src/) has most of the game logic in `App.vue`, with the exception of `RoundDetail.vue`. Is that an acceptable level of componentization, or should we look at splitting each part of our game that "does something" into a separate component?

For example, here's my p1 game:

[http://p1.kreinholz.me/](http://p1.kreinholz.me/)

I was thinking I could conceivably break it down into Single File Components as follows:

`App.vue`:

Intro and collapsible diagram of moves/outcomes

`Move.vue`:

The 5 possible moves, and the 'Attack!' button

`RoundResult.vue`:

Player's choice, Computer's choice, result (won/lost)

`ResultsTally.vue`:

Player wins vs. Computer wins

`WinningMoves.vue` (similar to RoundDetail):

Player's winning moves

The thing is, this seems like a lot of added complexity that doesn't really enhance such a simple game. But it also seems like good practice. However, without bringing in **Vuex**, which I'm thinking is beyond what I want to get into for p2, that leaves me potentially with a lot of **props** and **events** just to pass data back and forth, and potentially makes my simple little game _harder_ to understand and maintain. So I guess I'm wondering if I'm overthinking what to separate and whether I should just break down something truly reusable like the "Winning moves", or even add details to that component to turn it into something more like `RoundDetail.vue`, showing whether the Player or Computer won, the winning move (regardless of whether it was made by the Player or the Computer), and what move the Player and the Computer made.

I just think without **Vuex** my initial plan is turning into a state management nightmare. Any thoughts?

**Comment by kreinholz** [comment]
Update: I'm leaning toward keeping all the components, for practice, but putting most of my data in `App.vue` so as to avoid too many headaches.

Then I can make use of **props** and **emit** similar to the example for [`RoundDetail.vue`](https://github.com/susanBuck/e28/blob/master/week8spa/src/components/RoundDetail.vue)

**Comment by susanBuck** [comment]
@kreinholz - check out the simple "store pattern" described here:
https://vuejs.org/v2/guide/state-management.html

I'd categorize this as "state-management-light" - a precursor to more complex state management/apps that would start to benefit from Vuex.
