### ISSUE TITLE
Project 2 - Question

### ISSUE THREAD

**Issue by claudiomanuelboston** [susanBuck/e28-fall19#79]
Good morning, I have a couple of questions. I have not watched the latest lecture yet so I am not sure if that was covered or not?

1) Where can I get some information in regards to Integrated or Comprehensive approach?
2) For P1 I used a single file so I am not sure what I need to change?
3) We have the option of creating a new game instead of refactoring the old one as a single file, right?

Hope all is well with your family
Thanks
Claudio

**Comment by terichadbourne** [comment]
@claudiomanuelboston It looks to me from the project 2 instructions that we won't learn about integrated and comprehensive approaches to single-file components until week 8. Project 1 didn't use any components at all, and the components we learned about in week 6 were not single-file components, so we've not yet seen the specific approaches we'll need to choose between. In my experience, [single-file components](https://vuejs.org/v2/guide/single-file-components.html) actually mean that you use _multiple_ .vue files to create your single-page app, rather than defining all of your components in one place, so we'd definitely all need to do some refactoring for project 2 even if we stick with the same game. However, it does look to me like we're allowed to choose a new game if we'd like.

**Comment by susanBuck** [comment]
Hi @claudiomanuelboston - Watch the [**Week 6, Part 1** video posted on the 10th](https://hesweb.dev/e28/week/6) - it answers your questions. 

1. In the video I summarize what integrated/comprehensive means, and I note that I'll cover it in full details in week 8.
2. "Single file" and "Single file components" are not the same thing. "Single file components" is a strategy for building components that make them more modular. Also to be covered in Week 8.
3. Yes. Noted this in the video, and in the P2 project specs under **Stretch goals (Optional)** the last bullet point says *"Instead of refactoring your existing game, build a new game."*

**Comment by kreinholz** [comment]
@claudiomanuelboston, I too like staying ahead of deadlines, but I think waiting for Week 8, and _then_ diving into project2, will make our lives a lot easier. And, since we have the option to refactor our project1 submission, I see this as more of an opportunity to really practice Vue fundamentals and build a solid foundation, rather than something to stress over. I've been enjoying the course a lot so far, and expect Week 8 will be a lot of fun. Stay tuned!
